import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/db";
import { getOrCreateStripeCustomer, createCheckoutSession } from "@/lib/stripe";
import { getPlanById } from "@/config/pricing";

/**
 * POST /api/stripe/checkout
 * Creates a Stripe Checkout session for a client subscription.
 * Can be called by:
 *   - The client themselves (from their dashboard)
 *   - A PLATFORM_ADMIN on behalf of a client (passing clientId in body)
 */
export async function POST(req: NextRequest) {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "No autenticado" }, { status: 401 });

    const body = await req.json();
    const { plan, targetClientId } = body; // targetClientId only for admin use

    const selectedPlan = getPlanById(plan);
    if (!plan || !selectedPlan) {
        return NextResponse.json({ error: "Plan inválido. Usa: basic, business, premium" }, { status: 400 });
    }

    try {
        // Determine which client we're creating the subscription for
        let client: any;

        if (targetClientId) {
            // Admin creating subscription for another client
            const admin = await prisma.client.findUnique({ where: { clerkUserId: userId } }) as any;
            if (!admin || admin.role !== "PLATFORM_ADMIN") {
                return NextResponse.json({ error: "No autorizado" }, { status: 403 });
            }
            client = await prisma.client.findUnique({ where: { id: targetClientId } });
        } else {
            // Client creating their own subscription
            client = await prisma.client.findUnique({ where: { clerkUserId: userId } });
        }

        if (!client) return NextResponse.json({ error: "Cliente no encontrado" }, { status: 404 });

        // Get or create Stripe customer
        const stripeCustomerId = await getOrCreateStripeCustomer({
            clientId: client.id,
            email: client.email,
            businessName: client.businessName || client.email,
            existingCustomerId: client.stripeCustomerId,
        });

        // Save stripeCustomerId if new
        if (stripeCustomerId !== client.stripeCustomerId) {
            await prisma.client.update({
                where: { id: client.id },
                data: { stripeCustomerId }
            });
        }

        const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://www.citaliks.com";
        
        if (!selectedPlan.stripePriceId) {
            return NextResponse.json({ error: "El plan seleccionado no está configurado para pagos" }, { status: 500 });
        }

        const checkoutUrl = await createCheckoutSession({
            customerId: stripeCustomerId,
            priceId: selectedPlan.stripePriceId,
            plan: selectedPlan.id,
            clientId: client.id,
            setupPriceId: selectedPlan.stripeSetupId,

            successUrl: `${appUrl}/dashboard?subscription=success&plan=${plan}`,
            cancelUrl: `${appUrl}/dashboard?subscription=cancelled`,
        });

        // ── AUTOMATION: Send link to client if generated by Admin ────────────────
        if (targetClientId) {
            const { sendEmail } = await import("@/lib/email");
            const { sendSms } = await import("@/lib/sms");

            // 1. Send Email
            if (client.email) {
                await sendEmail({
                    to: client.email,
                    subject: "Enlace de suscripción a CitaLiks",
                    html: `
                        <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                            <h2 style="color: #2563eb;">¡Bienvenido a CitaLiks!</h2>
                            <p>Tu administrador ha generado un enlace de suscripción para el plan <strong>${plan}</strong>.</p>
                            <p>Para completar el alta y activar tu cuenta, por favor haz clic en el siguiente botón:</p>
                            <a href="${checkoutUrl}" style="display: inline-block; padding: 12px 24px; background-color: #2563eb; color: white; text-decoration: none; border-radius: 5px; font-weight: bold; margin-top: 10px;">Completar Pago y Suscripción</a>
                            <p style="margin-top: 20px; font-size: 12px; color: #666;">Si el botón no funciona, copia y pega este enlace en tu navegador:<br>${checkoutUrl}</p>
                        </div>
                    `
                });
            }

            // 2. Send SMS
            if (client.phone) {
                const smsMsg = `CitaLiks: Hola! Completa tu suscripción al plan ${plan} aquí: ${checkoutUrl}`;
                await sendSms(client.phone, smsMsg);
            }
        }

        return NextResponse.json({ success: true, url: checkoutUrl, sent: !!targetClientId });
    } catch (error: any) {
        console.error("[Stripe/Checkout] Error:", error);
        return NextResponse.json({ error: error.message || "Error al crear sesión de pago" }, { status: 500 });
    }
}
